# Keep building with gcc 10 for compatibility with packages
# that build R pacakges with CUDA (eg: xgboost)
c_compiler_version:        # [linux]
  - 10                     # [linux]
cxx_compiler_version:      # [linux]
  - 10                     # [linux]
fortran_compiler_version:  # [linux]
  - 10                     # [linux]
