version: 2

jobs:
  build_linux_c_compilergccfortran_compilergfortran:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilergccfortran_compilergfortran"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_c_compilertoolchain_cfortran_compilertoolchain_fort:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilertoolchain_cfortran_compilertoolchain_fort"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux_c_compilergccfortran_compilergfortran
      - build_linux_c_compilertoolchain_cfortran_compilertoolchain_fort
